name 'chef-conda'
maintainer 'Jose Luis Rivero'
maintainer_email 'jrivero@openrobotics.org'
license 'Apache-2.0'
description 'Install conda, miniconda, conda-forge'
long_description 'Works only on Windows by now'
version '0.0.1'
chef_version '>= 14.0'
